### PR TITLE
Facilitate tests by adding __init__.py and exclude it from setup

### PR DESCRIPTION
**Pull request by dzhuang**
I've moved `check.py` to relate directory, because those checks are at the project level, not belong to course module, though it is called when Course.app is ready.

### CODE REVIEW

**Comment by dzhuang** [comment]
I've move `check` to relate directory. It should be a project level module, not belong to course module, though it is called when Course.app is ready.

**Comment by dzhuang** [comment]
The change of structure:
image

**Comment by dzhuang** [comment]
This make it easier for write tests, e.g., make import, code auto-completion, and refactor more convinient.

**Comment by inducer** [comment]
Any reason for the `test` -> `tests` rename?

**Comment by inducer** [comment]
Looks fine otherwise.

**Comment by dzhuang** [comment]
Sorry, I felt it a tradition to add "s" for test folder? Because I see many projects (including [Django repo](https://github.com/django/django))  were using tests for unit tests. If you mind it, I'll revert that.

**Comment by inducer** [comment]
All my other projects use `test/`, but I'm flexible. The Django convention seems fine.

**Comment by dzhuang** [comment]
> All my other projects use test/

Sorry, I didn't know that.

**Pull request merged**
