### PR TITLE
Allow set mail (connection) for enrollment (request and decision).

### PR DESCRIPTION
**Pull request by dzhuang**
Sometimes we need to make those emails indepedent.

### CODE REVIEW

**Comment by inducer** [comment]
What will this do if someone upgrades and doesn't have the `enroll` email setting?

**Comment by dzhuang** [comment]
Then it will just work as before.

**Comment by dzhuang** [comment]
Sorry I should have addd some tests.

**Comment by inducer** [comment]
Looks good--let me know once you've got the tests in.

**Comment by dzhuang** [comment]
Overrided by #371

**Pull request closed without merging**
