### PR TITLE
add zh-CN locale

### PR DESCRIPTION
**Pull request by dzhuang**
include simplified Chinese translation.

### CODE REVIEW

**Comment by inducer** [comment]
Three small wrinkles:

* On line 69 of `django.po`, there is a blank translation.
* I don't think the binary compiled file `django.mo` should be included.
* Instead, the docs should tell the user to run `django-admin compilemessages`.

**Comment by dzhuang** [comment]
Blank translation means "don't translate". I leave them untranslated because I can't find accurate and compact words to express the same idea in Chinese.

**Comment by dzhuang** [comment]
updated.

**Comment by inducer** [comment]
Thanks very much for your contribution! (And thanks for explaining!)

**Pull request merged**
