### PR TITLE
Add notes for running celery 4 on Windows

### PR DESCRIPTION
**Pull request by dzhuang**
@inducer I've tested the latest commit (efdb51f19d7e11eb50658229d6696a72c2f510b4) on Windows, and find we need to add that instruction for Windows user. Is this patch ok?

### CODE REVIEW

**Comment by inducer** [comment]
LGTM. Thx!

**Comment by dzhuang** [comment]
Thank you!

**Comment by dzhuang** [comment]
(I've pushed to updated the docs on your site.)

**Comment by inducer** [comment]
Thanks!

**Pull request merged**
