### PR TITLE
Preapproval by inst_id

### PR DESCRIPTION
**Pull request by dzhuang**

### CODE REVIEW

**Comment by inducer** [comment]
I like the idea. That said, the migration needs to also convert over existing preapprovals to the new schema. Otherwise, I'd lose a bunch of preapproval data if I just ran this on the Illinois instance.

Here's an example of how to write a migration like that:

https://github.com/inducer/relate/blob/master/accounts/migrations/0007_migrate_user_status_data.py

**Comment by inducer** [comment]
Never mind, I take that back.

**Comment by inducer** [comment]
Thanks! Looks good to me.

**Comment by dzhuang** [comment]
Thanks, seems it will do no harm to exist preapproval data.

**Pull request merged**
