### PR TITLE
Added tests for versioning.py

### PR DESCRIPTION
**Pull request by dzhuang**
Also passed tests with dulwich == 0.18 (before changing the dependancy).

### CODE REVIEW

**Comment by dzhuang** [comment]
This should work around #492. @ishitatsuyuki @inducer What do you think of this?

**Comment by ishitatsuyuki** [comment]
Not a bad idea, but any reason for not using ParamikoSSHVendor?

**Comment by dzhuang** [comment]
I guess @inducer 's idea was to use a customized `progress_stderr` callback, but there's no interface to do that.

**Comment by ishitatsuyuki** [comment]
It looks like we can do that today (correct me if I'm wrong). Can we migrate?

**Comment by dzhuang** [comment]
Of course. I also think the code here can be moved to dulwich as a PR.

**Comment by dzhuang** [comment]
@ishitatsuyuki So do you think this is mergeable or you prefered to do something on the `dulwich` side (add that interface) ?

**Comment by ishitatsuyuki** [comment]
I would prefer adding the tests to dulwich instead, and simply migrate to dulwich's `ParamikoSSHVendor`.

**Comment by dzhuang** [comment]
Ok. However, I don't think my test (currenty unittest only) meet the requirement of `dulwcih`. Let's discuss at dulwich/dulwich#364.

**Comment by dzhuang** [comment]
@inducer Do you think  it's ok to migrate to  dulwich's built-in ParamikoSSHVendor?

**Comment by dzhuang** [comment]
https://github.com/dulwich/dulwich/pull/618

**Comment by dzhuang** [comment]
This would fail for dulwich 0.18, I'll update the dependency in a while.

**Comment by dzhuang** [comment]
Meged. Thanks for the suggestions @ishitatsuyuki . @inducer dulwich need to upgraded to 0.19 or above.

**Pull request merged**
