### PR TITLE
requirements: remove obsolete git dependencies

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Those dependencies should now have a packaged and fixed version.

### CODE REVIEW

**Comment by inducer** [comment]
I'm all in favor of this.

Before we merge this: Have you checked that their recent releases contain these fixes?

On a semi-related note, we should start using https://github.com/pypa/pipenv: #490.

**Comment by inducer** [comment]
And again, thanks for submitting this!

**Comment by ishitatsuyuki** [comment]
Yes I did. CI is also green so I probably got the things right.

**Comment by inducer** [comment]
Great, thanks! In it goes.

**Pull request merged**
