### PR TITLE
Hotfix: Fixed failed grade-internal-notes-notify

### PR DESCRIPTION
**Pull request by dzhuang**
The syntax is wrong. Moving the logic out side of template.

### CODE REVIEW

**Comment by dzhuang** [comment]
Todo: add tests.

**Comment by inducer** [comment]
Let me know when those tests are in.

**Comment by dzhuang** [comment]
I think it's done. The `codecov/patch` didn't reach 54.95% is due to the newly introduced diff on `use_masked_profile`, the tests of which is planned to be place in tests for `pperm` (which is a huge work) in the future.

**Comment by inducer** [comment]
LGTM, thx!

**Pull request merged**
