### PR TITLE
Added FAQ entry for changing things past deadlines

### PR DESCRIPTION
**Pull request by EnacheB**
There are many questions for how to do common things in RELATE from new TAs, I figured we should add this to the documentation.

### CODE REVIEW

**Comment by inducer** [comment]
Thanks! This is *almost* correct, in that it really depends on the rule set that a course. So it'd be good if you could add a "typically" to your sentence, along with that caveat.

I think we could also stand to section the FAQ into "Administration" (running/setting up an instance), "Content Creation", and "Course Operations".

**Comment by EnacheB** [comment]
Sounds good, but what do you mean by "rule set"?

**Comment by inducer** [comment]
https://documen.tician.de/relate/flow.html#flow-rules

**Comment by inducer** [comment]
Thanks!

**Comment by inducer** [comment]
(Docs should update automatically in a bit.)

**Pull request merged**
