### PR TITLE
only chunks which are .shown should be listed.

### PR DESCRIPTION
**Pull request by dzhuang**

### CODE REVIEW

**Comment by inducer** [comment]
This filtering is actually done here:

https://github.com/inducer/relate/blob/master/course/content.py#L708

Did you encounter a situation where something slipped through?

**Comment by dzhuang** [comment]
Yes. The object passed to  the template seems to be not filtered,  ``for chunk in course_desc.chunks``.

**Comment by inducer** [comment]
Where? The course page view uses the function I pointed to above:

https://github.com/inducer/relate/blob/master/course/views.py#L132

**Comment by dzhuang** [comment]
Sorry for my bad expressions. It's not about the contents rendered in course page, but the title hyperlink in the dropdown menu.

https://github.com/inducer/relate/blob/master/course/templates/course/course-page.html#L8

I now think my solutions is not so good, this line can be simply changed to:

```
{% for chunk in chunks %}
```

**Comment by inducer** [comment]
Good catch, fixed in 120e619.

**Pull request closed without merging**
