### PR TITLE
Fix template overriding continued

### PR DESCRIPTION
**Pull request by dzhuang**
Add back {% block header_extra %}{% endblock %} to base.html

### CODE REVIEW

**Comment by dzhuang** [comment]
Todo: Add test the ensure those assets are included in specific views.

**Comment by inducer** [comment]
Is this ready to merge, despite the "Todo" comment? If not, please add [WIP] to title.

**Comment by dzhuang** [comment]
It's ready, but I will add tests later.

**Comment by inducer** [comment]
Sounds good. Thanks for the quick response (and the patch)!

**Comment by dzhuang** [comment]
Off the topic. (I always try to respond in time. But you know I'm using Gmail which is banned here (that posed some lag) and there's timezone between us.)

**Pull request merged**
