### PR TITLE
fp parsing

### PR DESCRIPTION
**Pull request by beesor**

### CODE REVIEW

**Comment by inducer** [comment]
Remember how I was confused about this not working on your machine? So what I found when I tried this on my machine is that it parsed `1e-4` just fine, even without your patch. To help shed some light on the mystery, could you please try the following on your machine, 

```
(in your relate checkout)
$ git checkout 86f437b7ef3fe4bcc3dd1597e6d39815b6d5eb30
$ python
>>> import os
>>> os.environ.setdefault("DJANGO_SETTINGS_MODULE", "relate.settings")
'relate.settings'
>>> 
>>> import django
>>> django.setup()
>>> from course.page.text import float_or_sympy_evalf
>>> float_or_sympy_evalf(1e-5)
1e-05
```
in particular I'm interested in the output of the last line, which for me just works without your patch. So, I'm wondering what goes wrong on a Mac.

After this is all done, do:
```
git checkout master
```
to revert to the version with the fix applied.

Thanks for your help!

**Comment by beesor** [comment]
that seemed to work just find using that checkout of relate,

: git checkout 86f437b7ef3fe4bcc3dd1597e6d39815b6d5eb30
Note: checking out '86f437b7ef3fe4bcc3dd1597e6d39815b6d5eb30'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 86f437b... Move gradebook buttons to top
: python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ.setdefault("DJANGO_SETTINGS_MODULE", "relate.settings")
'relate.settings'
>>> import django
>>> django.setup()
>>> from course.page.text import float_or_sympy_evalf
>>> float_or_sympy_evalf(1e-5)
1e-05

thoughts?

ryne

**Comment by inducer** [comment]
Sorry, I messed that up. The last line should be:

```
>>> float_or_sympy_evalf("1e-5")
```

**Comment by beesor** [comment]
>>> float_or_sympy_evalf("1e-5")  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "course/page/text.py", line 393, in float_or_sympy_evalf
    return float(parse_sympy(s).evalf())
  File "course/page/text.py", line 319, in parse_sympy
    return PymbolicToSympyMapper()(parse(s))
  File "/Library/Python/2.7/site-packages/pymbolic/parser.py", line 453, in __call__
    result = self. parse_expression(pstate, min_precedence)
  File "/Library/Python/2.7/site-packages/pymbolic/parser.py", line 238, in parse_expression
    left_exp = self.parse_prefix(pstate)
  File "/Library/Python/2.7/site-packages/pymbolic/parser.py", line 233, in parse_prefix
    left_exp = self.parse_terminal(pstate)
  File "/Library/Python/2.7/site-packages/pymbolic/parser.py", line 181, in parse_terminal
    return self.parse_float(pstate.next_str_and_advance())
  File "/Library/Python/2.7/site-packages/pymbolic/parser.py", line 172, in parse_float
    return float(s.replace("d", "e").replace("D", "e"))
ValueError: invalid literal for float(): 1e

**Comment by inducer** [comment]
Ah, I see what's going on. Thank you very much for trying that. This particular thing was fixed by this commit here:

https://github.com/inducer/pymbolic/commit/998397dc2c0ec4d0493280eefce6f00f0d76dc14

That's why I did not see this on my machine. The commit itself is not a part of any release of that software, and so you ended up getting the unfixed version. I'll go ahead and "double-fix" this issue: I will go ahead and release that piece of software, and I'll also merge your patch. Thanks again for your patience in helping me figure out what was going on.

**Comment by dzhuang** [comment]
I tried the following code in sandbox, but TypeError will be raised with whatever I input.

```
        type: TextQuestion
        id: float_trial
        value: 0
        prompt: |

            # float
            
            1/1000 equals  ___________________.

        answers:

          - type: float
            value: 0.001
            rtol: 0.0001

```

**Comment by inducer** [comment]
@dzhuang Fixed in 0ada92c, sry.

**Pull request merged**
