### PR TITLE
Fix error when cache is not enabled.

### PR DESCRIPTION
**Pull request by dzhuang**

### CODE REVIEW

**Comment by dzhuang** [comment]
The ci failure of appveyor can be fixed by https://github.com/inducer/django-bootstrap3-datetimepicker/pull/5. And the failure of travis (and your gitlab instance), need to update `setuptools` as suggested at https://github.com/knaperek/djangosaml2/pull/109#issuecomment-336948465

**Comment by inducer** [comment]
As of cfdb4c72c2d689359b42f3f908872354deb9745f, it's using an upgraded setuptools.

**Comment by dzhuang** [comment]
@inducer  Thank you for the fix!

**Comment by dzhuang** [comment]
@inducer can you review this PR? Thanks.

**Comment by inducer** [comment]
Thanks! Sorry this fell through the cracks.

**Comment by dzhuang** [comment]
NVM. Thanks.

**Pull request merged**
