### PR TITLE
Extending email settings

### PR DESCRIPTION
**Pull request by dzhuang**
1. Allow using email services which don't allow non-authorized sender, fixing #41 and #195
1. Allow multiple smtp, inspired by https://gist.github.com/niran/840999
1. Preparing for #237.

### CODE REVIEW

**Comment by inducer** [comment]
Looks good. Thanks for the patch.

**Comment by inducer** [comment]
FWIW, to avoid mistakes, Relate now gets tested with [mypy](http://mypy-lang.org) on every commit, and it's expected to pass. See `run-mypy.sh`. This commit broke that--see f53336ec for a fix. I've also renamed `get_connection` to `get_outbound_mail_connection`.

**Comment by inducer** [comment]
This also broke the syntax in `local_settings.py.example`:
```
  File "local_settings.py", line 143
    "student_interact": {
                     ^
SyntaxError: invalid syntax
```

Please be more careful.

**Comment by dzhuang** [comment]
Thank's for the information, I'll try to do the test before submitting a PR in the future, and sorry for the errors.

**Comment by inducer** [comment]
Np. Thanks for submitting patches!

**Comment by inducer** [comment]
d8644cb has more fixes for this that broke for me in production.

**Pull request merged**
