### PR TITLE
Remove non exist static references.

### PR DESCRIPTION
**Pull request by dzhuang**
Since the introduction of `django-bootstrap-datepicker-plus`, those links were no longer valid.

### CODE REVIEW

**Comment by inducer** [comment]
Thanks! These changes are already part of #892, which I am hoping to merge over the next week or so. As a result, I think I would prefer to merge them via that route. In fact, the only thing that's missing in #892 from my perspective are some rendering issues with the `InlineMultiQuestion`, specifically the various tooltip and right/wrong indicators. If you are able, it would be super helpful if you could take a look at that since you know that code better than me, and, perhaps, submit a PR targeting the `bs5` branch.

**Comment by dzhuang** [comment]
Thanks. I guess the issue you mentioned is the removal of `glyphicons` in Bootstrap 5, I'll try to work on that in a few days.

**Comment by inducer** [comment]
It's not so much the glyphicons, it's all the popup/over/under logic and the field layout which has changed substantially in bs5.

**Comment by dzhuang** [comment]
This PR is closed in favor of #949.

**Pull request closed without merging**
