### PR TITLE
Improvements for circumstances where strict partial correctness are needed

### PR DESCRIPTION
**Pull request by dzhuang**

### CODE REVIEW

**Comment by inducer** [comment]
If you want this, I'm not going to stand in the way. I'd like to request that you rename it `allow_partial_credit_subset_only` (or something). 'Strict' isn't quite specific enough to my mind.

**Comment by dzhuang** [comment]
thanks for your suggestion, I will modify that asap.
2015年9月25日 下午9:11，"Andreas Klöckner" <notifications@github.com>写道：

**Comment by dzhuang** [comment]
Is that PR ok? thx.

**Comment by inducer** [comment]
Looks good, thanks!

**Pull request merged**
