### PR TITLE
Add site-specific settings(warning/error) for deprecated custom pages.

### PR DESCRIPTION
**Pull request by dzhuang**

### CODE REVIEW

**Comment by dzhuang** [comment]
cc @inducer What do you think about this PR?

**Comment by inducer** [comment]
Seems fine. Some questions:

* I wonder whether we should really publicly document this. (I'd rather not.)
* How about allowing enforcement of earlier deadlines but "at the lastest 2019"? I'd like to avoid having this drag out.
* Is anyone on your end making heavy use of these things?

**Comment by dzhuang** [comment]
> I wonder whether we should really publicly document this. (I'd rather not.)
 
Agreed.

> How about allowing enforcement of earlier deadlines but "at the lastest 2019"? I'd like to avoid having this drag out.

Agreed.

> Is anyone on your end making heavy use of these things?

Me only. But I can migrate those pages without problem.

**Comment by dzhuang** [comment]
I'll remove that from docs, and update the settings.

**Comment by dzhuang** [comment]
Updated.

**Comment by dzhuang** [comment]
Also, should this be removed?
> Instructors can implement custom question/page types in Python.

**Comment by inducer** [comment]
> Also, should this be removed?

Yes, definitely.

**Comment by inducer** [comment]
LGTM aside from the doc/README removal.

**Comment by dzhuang** [comment]
>> Also, should this be removed?

> Yes, definitely.

Done. And I think it's ok to merge.

**Pull request merged**
