### PR TITLE
Fix validation check for duplicate (kind, no-ordinal) events

### PR DESCRIPTION
**Pull request by inducer**
cc @dzhuang

### CODE REVIEW

**Comment by dzhuang** [comment]
Thanks. I'll fix the test in a while. P.S., What about #584 ?

**Comment by inducer** [comment]
> Thanks. I'll fix the test in a while.

Thanks!

**Comment by inducer** [comment]
> What about #584?

Sorry, lost track of it. Will take a look now.

**Comment by inducer** [comment]
@dzhuang Codecov seems to have broken. Any clue what happened there?

**Comment by inducer** [comment]
(Merging because I don't think the current set of changes has anything to do with codecov)

**Comment by dzhuang** [comment]
Thanks!

**Pull request merged**
