### PR TITLE
for py3.x, urljoin is in urllib.parse

### PR DESCRIPTION
**Pull request by dzhuang**

### CODE REVIEW

**Comment by inducer** [comment]
Can you use `six` for that?

http://pythonhosted.org/six/#module-six.moves.urllib.parse

**Comment by dzhuang** [comment]
Thanks for the information!

**Comment by dzhuang** [comment]
Updated.

**Comment by inducer** [comment]
Just import `six` directly, not via Django. (Sorry to be going on about this minor point.)

**Comment by dzhuang** [comment]
Nvm. I've originally import it directly from six, and the switched to Django after I noticed some part of your code is importing from django :-). Modified to ``six`` now.

**Comment by inducer** [comment]
Thx!

**Pull request merged**
