### PR TITLE
l10n for DataTable.

### PR DESCRIPTION
**Pull request by dzhuang**
Show localized literals on DataTable plugins.

### CODE REVIEW

**Comment by inducer** [comment]
I like this, but for legal reasons I can't use the CDN in the US. Can you change this to add the DataTable l10n packages to the bower packages in `relate/settings.py`?

**Comment by dzhuang** [comment]
May I add this line in ``BOWER_INSTALLED_APPS``
```
"datatables-plugin=https://github.com/DataTables/Plugins.git",
```
 That project has not yet been integrated into bower yet. https://github.com/DataTables/Plugins/search?q=bower&type=Issues&utf8=%E2%9C%93

**Comment by dzhuang** [comment]
I've made it too complicated, just found https://github.com/Haixing-Hu/datatables-i18n in bower.

**Comment by dzhuang** [comment]
Is it ok now?

I also found django-select2 is using CDN provided by select2, shall I provide a PR to use local static files?

**Comment by inducer** [comment]
Yep, that looks good. Thanks!

**Comment by inducer** [comment]
I'd appreciate a PR to make select2 be static. Thanks for offering!

**Pull request merged**
