### PR TITLE
Migrate testing to pytest

### PR DESCRIPTION
**Pull request by joshuata**
I saw that #672 had stalled. This is a basic implementation of pytest integration including automatically load the postgres tests if it is connected to a postgres database.

If a user runs `pytest`, it will run the fast tests, `pytest --slow` runs the slow tests, and `pytest --all` runs all tests.

I would recommend migrating to [FactoryBoy](https://factoryboy.readthedocs.io/en/latest/introduction.html) over the next while since it would replace a lot of the setup/teardown functions and the mixin classes and replace them with native pytest fixtures that allow much easier customization.

### CODE REVIEW

**Comment by joshuata** [comment]
@inducer If you run the complete test suite with postgres as the database there are lots of failures. Is that expected behavior?

```
FAILED tests/test_calendar.py::ViewCalendarTest::test_all_day_event
FAILED tests/test_calendar.py::ViewCalendarTest::test_event_has_end_time - As...
FAILED tests/test_calendar.py::ViewCalendarTest::test_events_file_with_events_test1
FAILED tests/test_calendar.py::ViewCalendarTest::test_events_file_with_events_test2
FAILED tests/test_calendar.py::ViewCalendarTest::test_events_file_with_events_test3
FAILED tests/test_calendar.py::ViewCalendarTest::test_hidden_event_not_shown
FAILED tests/test_calendar.py::ViewCalendarTest::test_no_event_file - Asserti...
FAILED tests/test_exam.py::ExamFacilityMiddlewareTest::test_already_locked_down
FAILED tests/test_exam.py::ExamLockdownMiddlewareTest::test_flow_page_related_view_not_ok
FAILED tests/test_exam.py::ExamLockdownMiddlewareTest::test_flow_page_related_view_ok
FAILED tests/test_exam.py::ExamLockdownMiddlewareTest::test_ok_views - Assert...
FAILED tests/test_exam.py::ExamLockdownMiddlewareTest::test_ok_with_saml2_views
FAILED tests/test_exam.py::ExamLockdownMiddlewareTest::test_ok_with_select2_views
FAILED tests/test_exam.py::ExamLockdownMiddlewareTest::test_relate_exam_lockdown
FAILED tests/test_exam.py::ExamLockdownMiddlewareTest::test_start_flow_not_ok
FAILED tests/test_exam.py::ExamLockdownMiddlewareTest::test_start_flow_ok - A...
FAILED tests/test_flow/test_flow.py::ExpireFlowSessionTest::test_invalid_expiration_mode
FAILED tests/test_flow/test_flow.py::ViewFlowPageTest::test_prev_visit_id_after_post
```

**Comment by inducer** [comment]
> I would recommend migrating to FactoryBoy over the next while since it would replace a lot of the setup/teardown functions and the mixin classes and replace them with native pytest fixtures that allow much easier customization.

I'm very much in favor of that.

> I saw that #672 had stalled.

Yeah. I wanted to make it go, but I ran out of time then.

>  If you run the complete test suite with postgres as the database there are lots of failures. Is that expected behavior?

Definitely not! What do the tracebacks look like?

**Comment by joshuata** [comment]
If you look at the logs of the postgres test for https://github.com/inducer/relate/pull/713/commits/fcf9bb9211693b81686eade0e0b5df8ddbfb50f6 you can see where they are. It looks like the problem may be due to postgres enabling additional parallelism that sqlite doesn't handle.

For example, `ExamLockdownMiddlewareTest` will fail if run with the rest of the file `test/test_exam.py`, but not if just the single class is run. The error returned is `course.models.FlowSession.DoesNotExist: FlowSession matching query does not exist.`

**Comment by inducer** [comment]
Thanks for working on this! I like this change a lot and propose that we merge it asap. To enable that, it might be useful to xfail the failing tests when running on postgres and play whack-a-mole with them later on. What do you think?

A number of the postgres failures seem to make assumptions about the IDs of things. That's just incorrect and should be fixed (by removing those assumptions). Others (the 302->403 ones) look more subtle. Maybe @dzhuang has some ideas?

**Comment by dzhuang** [comment]
About the postgres test failure, I am not sure right now. From a brief glance at the calendar test view, it seems the data were not reset between tests? Not sure. I need a while before I can run those tests on my machine.

@joshuata Thank you for working on this.

**Comment by joshuata** [comment]
I added a [devcontainer file](https://code.visualstudio.com/docs/remote/containers) if you are interested in using Visual Studio Code and docker to run the tests. It includes a postgres container as well, which is what I've been using to do local troubleshooting

**Comment by dzhuang** [comment]
@joshuata I've pushed a PR to your PR, sorry for the looong delay.

**Comment by inducer** [comment]
> This should probably be moved into a cron-like action in the future

Won't it run weekly on account of [this](https://github.com/inducer/relate/blob/b04887be7330107943519594af6bd26886a6d1a9/.github/workflows/ci.yml#L9-L10)?

**Comment by inducer** [comment]
> Adds security advisory checking

Thx! (Didn't know this existed, but Github does regularly yell at me if there's an unsafe dep)

**Comment by inducer** [comment]
Thanks for working on this! LGTM, in it goes.

**Pull request merged**
